// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import FormMapController from "./form_map_controller"
application.register("form-map", FormMapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ReviewFormController from "./review_form_controller"
application.register("review-form", ReviewFormController)

import ShowMapController from "./show_map_controller"
application.register("show-map", ShowMapController)
